### ISSUE TITLE
alpinelinux.org offline

### ISSUE THREAD

**Issue by nivong** [gliderlabs/docker-alpine#209]
Just a note: alpinelinux.org is offline !

**Comment by Multiply** [comment]
dl-cdn.alpinelinux.org works, but has problems actually downloading anything.

**Comment by Multiply** [comment]
This should now be resolved. https://status.fastly.com/incidents/0523znjnppc4

**Comment by apertureless** [comment]
https://pkgs.alpinelinux.org/ seems offline, too

**Comment by pydolan** [comment]
I'm still having issues downloading from dl-cdn.alpinelinux.org. Docker was hanging at the initial alpine fetch (`fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz`), but then I restarted my docker machine, and now the download errors actually show:

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/community: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
```

Of course, visiting these URLs via browser download them without an issue.

**Comment by RRAlex** [comment]
Seems to be back ?

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.167438ca.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.4/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.a2e6dac0.tar.gz: No such file or directory
```

**Comment by luyi985** [comment]
Same issue
I'm sitting behind a proxy, and have added proxy exports in /etc/default/dock
now stuck at
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz

**Comment by jhg** [comment]
I have same problem:
```
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/community: temporary error (try again later)
```

**Comment by gittycat** [comment]
Same problem since two days ago.
Alpine 3.4
```
/ # apk --no-cache add gnupg
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  gnupg (missing):
    required by: world[gnupg]
```

**Comment by ncopa** [comment]
@gittycat can you `nslookup dl-cdn.alpinelinux.org`?

**Comment by gittycat** [comment]
@ncopa 
```
/ #  nslookup dl-cdn.alpinelinux.org
nslookup: can't resolve '(null)': Name does not resolve
```

**Comment by ncopa** [comment]
> ````
> nslookup dl-cdn.alpinelinux.org
> nslookup: can't resolve '(null)': Name does not resolve
> ````

This means DNS resolution is not working. Your network setup is broken somehow.

**Comment by gittycat** [comment]
@ncopa It is indeed the problem. The container didn't have an internet facing network interface. Thanks a lot for your help.

**Comment by jhg** [comment]
I fixed it in my docker container using `--network=host`

**Comment by therealkkeene** [comment]
This issue is occurring for me as well. It appears intermittent. I sometimes get a 503 when running a wget on http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz or http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz sometimes I can pull the file down on my local. This is failing in a jenkins job for a docker setup. Getting ```fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)``` and then if I wait a few minutes it might work. I also went to http://dl-cdn.alpinelinux.org/alpine and then when I open version# into a new tab, sometimes the link opens and other times 503 timeout errors.
<img width="441" alt="screen shot 2017-03-15 at 4 54 02 pm" src="https://cloud.githubusercontent.com/assets/6775037/23970414/0beef87a-09a0-11e7-8ebf-00bd09dcd726.png">

**Comment by gary-rowe** [comment]
I'm getting this too:
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.c51f8f92.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.d09172fd.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  drill (missing):
    required by: world[drill]
```

Just a repo glitch?

**Comment by ncopa** [comment]
yes, temporary glitch in the fastly service. https://status.fastly.com

**Comment by ningyougang** [comment]
thinks, this helps a lot!!^^

**Comment by dkirrane** [comment]
I'm hitting this too.
Hangs on `fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz`
