### ISSUE TITLE
Temporary error (try again later)

### ISSUE THREAD

**Issue by rommik** [gliderlabs/docker-alpine#334]
I run into this issue when building a docker image on Ubuntu Host.
The Same build on Windows 10 using docker-tools CLI (so technically inside a VirtualBox VM) has no issues and Docker images are built correctly.

I have reinstalled Docker on my Ubuntu completely to have a fresh version just in case. 
Any suggestions what else I can do to troubleshoot this issue?

Build command output
````
Sending build context to Docker daemon  572.4kB
Step 1/15 : FROM alpine:edge
edge: Pulling from library/alpine
cc5efb633992: Pull complete 
Digest: sha256:2b796ae57cb164a11ce4dcc9e62a9ad10b64b38c4cc9748e456b5c11a19dc0f3
Status: Downloaded newer image for alpine:edge
 ---> f96c4363411f
Step 2/15 : RUN apk add --update nodejs
 ---> Running in 12865b082f34
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.066df28d.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.b53994b4.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  nodejs (missing):
    required by: world[nodejs]
The command '/bin/sh -c apk add --update nodejs' returned a non-zero code: 1

````

My dockerfile
````
FROM alpine:edge
RUN apk add --update nodejs

#create an app directory
RUN mkdir -p /app
WORKDIR /app

# create some useful folders
RUN mkdir -p /data

# Copy apps build in another folder
COPY main.js /app
COPY package.json /app
COPY version.json /app
COPY dist /app/dist
COPY data /data
COPY app_modules /app/app_modules
COPY node_modules /app/node_modules

#expose the port
EXPOSE 5555

#start the app
#ENV NODE_ENV=development
#ENV debug=true

WORKDIR /app

# comment if need a console in the container
CMD [ "node", "main.js" ]

````

**Comment by andyshinn** [comment]
This keeps popping up in other threads and I wonder if there might be a change in the way Fastly is doing DNS. To debug this we really need to see the output of something like `curl -v -s http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz > /dev/null` to get headers and the HTTP response from within a container. My guess is a temporary issue with a Fastly POP or a change in POP IP address that hasn't yet properly timed out in Docker DNS proxy yet.

**Comment by rommik** [comment]
@andyshinn I'll see if I can provide you with the output. However, I believe the issue is in Docker Engine, and possibly in DNS caching. My Host Machine was on the corporate network 1, but when we switched it to corporate network 2, the issue was gone. 
After speaking to networking people, they weren't able to tell how the difference between networks could have affected the Docker Build. It points to a combination of DNS and Docker Engine. However, we ruled out the DNS, because on both networks we were able to do curl from the host and download the .gz files.

I checked my docker config and its DNS is set to 8.8.8.8 and 8.8.4.4. From both networks these IPs are reachable.

**Comment by andyshinn** [comment]
I think it is related to #279 which has more history. I think maybe when Fastly changes server IPs they may be redirecting with a 301, which causes `apk` to choke. But this is why I want to output to see where it is redirecting. I'm not sure if it comes from Fastly or a broken upstream server.

**Comment by rlewkowicz** [comment]
So I'm having dns issues, but my results are different. My stuff just hangs at getting packages. 
https://www.whatsmydns.net/#A/mirrors.aliyun.com

This is the mirror mine tries to use. 
```
curl -vvvv -s http://mirrors.aliyun.com/alpine/v3.5/main/x86_64/APKINDEX.tar.gz > /dev/null
*   Trying 124.47.11.88...
* Connected to mirrors.aliyun.com (124.47.11.88) port 80 (#0)
> GET /alpine/v3.5/main/x86_64/APKINDEX.tar.gz HTTP/1.1
> Host: mirrors.aliyun.com
> User-Agent: curl/7.47.0
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
```
It will just hang here indefinitely in docker (at least for an hour+) and the curl times out. This is from my laptop:

```
recipes: curl -vvvv -s http://mirrors.aliyun.com/alpine/v3.5/main/x86_64/APKINDEX.tar.gz > /dev/null
*   Trying 219.147.157.84...
* TCP_NODELAY set
* Connected to mirrors.aliyun.com (219.147.157.84) port 80 (#0)
> GET /alpine/v3.5/main/x86_64/APKINDEX.tar.gz HTTP/1.1
> Host: mirrors.aliyun.com
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Tengine
< Content-Type: application/octet-stream
< Content-Length: 732690
< Connection: keep-alive
< Date: Wed, 27 Sep 2017 13:45:47 GMT
< Last-Modified: Thu, 21 Sep 2017 10:13:30 GMT
< ETag: "59c390ca-b2e12"
< Expires: Wed, 27 Sep 2017 13:50:47 GMT
< Cache-Control: max-age=300
< Accept-Ranges: bytes
< Via: cache14.l2nu29[36,304-0,H], cache32.l2nu29[38,0], cache2.cn547[0,200-0,H], cache6.cn547[1,0]
< Age: 18
< X-Cache: HIT TCP_MEM_HIT dirn:3:81977809 mlen:-1
< X-Swift-SaveTime: Wed, 27 Sep 2017 13:45:48 GMT
< X-Swift-CacheTime: 120
< Timing-Allow-Origin: *
< EagleId: db939d4615065199657165411e
<
{ [12630 bytes data]
* Curl_http_done: called premature == 0
* Connection #0 to host mirrors.aliyun.com left intact
```

 @andyshinn this may be a different issue. But it's DNS related, and works one place but not the other. This is from my system, but if you need it from inside docker, I can provide it.

**Comment by rlewkowicz** [comment]
Other mirrors do work. I suppose I have to go dig and see if they hard coded a mirror or something. It's odd though that it breaks apk so hard. I suppose I would have thought it to be more resilient

**Comment by matkam** [comment]
I was seeing this error on my [Drone](https://drone.io/) build server, running on Kubernetes. By default it users "Docker-in-Docker" (dind) for builds. The error went away after I disabled dind on the Drone server.

**Comment by matkam** [comment]
@Zest-nikunj sure. My Drone server was deployed by a Helm chart to a Kubernetes cluster: https://github.com/kubernetes/charts/tree/master/incubator/drone
I just redeployed it, setting `dind.enabled` to `false`. I'd imagine if you're not using Helm or Kubernetes, you'd have to mount the host's docker socket on the drone agent's container: https://github.com/kubernetes/charts/blob/master/incubator/drone/templates/deployment-agent.yaml#L52

**Comment by Zest-nikunj** [comment]
Thanks @matkam. We are not on Kubernetes and the settings seem correct but we continue to have the issue. We will investigate further. If needed, I shall come back to you. Thanks again.

**Comment by publicocean0** [comment]
same problem ... before i resolved with reboot. Now it is not working

**Comment by tdhawan** [comment]
Same problem, just kept on re-trying, and 3rd time it went thru. seems like there is a bad server which the load balancer hits.

**Comment by rogerluiz** [comment]
same error here

**Comment by markk12** [comment]
same problem here . I tried many many times ... it is not a bad server ... it seams a bug

**Comment by wlechowicz** [comment]
Hit the same problem (again) and tried many suggested (in #279) suggestions, involving changing apk settings in Dockerfile and such. but nothing helped. What did help finally was to restart Docker and then apk just pulled the APKINDEX like nobody's business.

**Comment by CharlesStover** [comment]
I get this as well on my workstation using Docker for Windows. Using a mirror did not help.

**Comment by brunowdev** [comment]
I had this error with Gitlab, i just change docker build command to run with --network host option and it works!

**Comment by EvgeniGordeev** [comment]
`sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf` helped on Ubuntu 16 build agent to make CI jobs build alpine based docker images again as per https://github.com/gliderlabs/docker-alpine/issues/279#issuecomment-411982620

**Comment by montao** [comment]
@EvgeniGordeev That solution worked for me too, running Windows 10 host + Ubuntu 18.04 with Vagrant and alpinelinux in a docker container in the Ubuntu.

**Comment by hezzze** [comment]
@wlechowicz restart docker service solved my issue 👍

**Comment by jbcurtin** [comment]
@andyshinn , RE: https://github.com/gliderlabs/docker-alpine/issues/334#issuecomment-330096922

It was a DNS error for me. By setting `/etc/docker/daemon.json` with,
```
{
  "dns": ["8.8.8.8"]
}
```

and then restarting docker with,
```
sudo service docker restart
```

I was able to build images again.

**Comment by hackaugusto** [comment]
Just for reference, I got a similar error, but in my case it was a problem with nftables:

```
 ---> Running in 2522cf9dc903
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
```

Stopping nftables and restarting docker will give the container internet access.

**Comment by ShayBox** [comment]
Same problem, neither of the previous fixes it.

**Comment by OkumuraShintarou** [comment]
Since there are times when the bridge is disturbing, it is successful if you execute it as host.
`docker build -t hoge:latest . --network=host`

**Comment by When-Jay** [comment]
restarting docker service maybe help you

**Comment by GreyDev** [comment]
Same issue. Not using docker at all. Not using any external services at all either. DNS and package mirrors are on my local network. Building using the mkimg scripts. I've also tried setting the mirror ip/hostname in /etc/hosts.

I can reliably replicate the failure using a completely fresh install of (a slighly custom) Alpine. I'm not running in a virtualised/containerised environment - it's a phyiscal server. I can provide any further information requested.

**Comment by akarimvnera** [comment]
Run docker build command to run with --network=host option and it works

**Comment by rvillane** [comment]
any idea how to add this workaround using docker-compose ?  the --network flag is not available there

**Comment by dacoburn** [comment]
I just ran into this, everything had been working fine on:

Windows 10 host with Hyper-V
Ubuntu 18.04 Guest
Docker in the Ubuntu 18.04

Suddenly `apk` and `go mod download` started failing. The APK issue was the temporary error.  Did the fix suggested in this comment https://github.com/gliderlabs/docker-alpine/issues/334#issuecomment-450598069 and everything was working again. DNS Was working fine on the guest and the host, only when building the docker containers was I having issues.

**Comment by TakumiInui5432** [comment]
same error

**Comment by half-bread-pin** [comment]
same error

Ubuntu in VMware
Docker in the Ubuntu 18.04

change virtual machine's network setting to NAT mode, and it works

**Comment by TakumiInui5432** [comment]
> same error
> 
> Ubuntu in VMware
> Docker in the Ubuntu 18.04
> 
> change virtual machine's network setting to NAT mode, and it works

It is usually caused by the local network, try to reboot

**Comment by SvetaO** [comment]
> any idea how to add this workaround using docker-compose ? the --network flag is not available there

 same problem. It will be great if someone can advise. Restarting docker or reboot is no go for my case

**Comment by samuelfusato** [comment]
> 
> 
> Since there are times when the bridge is disturbing, it is successful if you execute it as host.
> `docker build -t hoge:latest . --network=host`

Solved using:

$ docker build . -t rancher-demo --network=host 

Thank YOU!

**Comment by onepushmain** [comment]
> any idea how to add this workaround using docker-compose ? the --network flag is not available there

Same problem. I'm using Manjaro and none of the solutions worked for me

**Comment by TakumiInui5432** [comment]
I have encountered this problem before. The reason is that docker cannot access the external network. Maybe the internal network has designated a private DNS server, so it is necessary to configure daemon.json

**Comment by onepushmain** [comment]
I solved using this: https://github.com/docker/for-linux/issues/957#issuecomment-627166787

Using Manjaro, one of the first things I do is install firewalld, but it's configured with nftable by default.
I changed it to iptables and then it was fixed.

1. `vim  /etc/firewalld/firewalld.conf`
2. change `FirewallBackend=nftables` to `FirewallBackend=iptables`
3. restart the service of firewalld with `sudo systemctl restart firewalld.service`

**Comment by AnatoleLucet** [comment]
If you're building an image via docker-compose you might try the following to use the host network at build time:
```yml
version: "3.7"

services:
  my_service:
    build:
      context: .
      network: host # this line is the trick
```

**Comment by chanon** [comment]
On WSL2 I've been building docker images successfully for months, but today suddenly I'm getting this error. Tried --network=host and it is still not working. Rebooted a few times too.

A wget of the url from inside WSL2 command line works, so WSL2 network connectivity is fine.

Not sure how to fix it.

EDIT: Edited the dns in the daemon.json file to local router one, and made sure the network in Windows was set to Private and then rebooted and it worked!

**Comment by knrchowdary** [comment]
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  python (no such package):
    required by: world[python]

 Getting above error while running command from .gilab-ci.yml
 
 FYI command: apk add --no-cache python py-pip bash gawk sed grep bc coreutils

**Comment by minecraftchest1** [comment]
I took a quick look, and apparently there is a 301 from HTTPS to HTTP.

**Comment by minecraftchest1** [comment]
I am still seeing this error. I have a docker image that I **CANNOT BUILD** because of this. If the problem is with the CDN, **USE ANOTHER CDN! ** Software users should not be forced to suffer from upstream issues just because upstream won't do anything about it.

**Comment by ryukoposting** [comment]
@minecraftchest1 Just got the 'temporary error' problem myself:

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  ...
```

I tried a few different solutions, including explicitly defining DNS servers in the docker-compose file and in /etc/docker/daemon.json, to no avail.

For me, adding `network: host` to my docker-compose file fixed the problem:
```yaml
version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ...
      network: host    <--- this fixed it
```

**Comment by minecraftchest1** [comment]
I have tried --network host with my docker build command which still doesn't solve it for me. I don't use docker compose.

**Comment by tropicoo** [comment]
For Raspberry Pi:

> The answer is this: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
> (alpine 3.13 isn't compatible with raspberry pi os by default due to some outdated package)

[[source](https://github.com/docker/for-linux/issues/1196#issuecomment-774490539)]

> For Raspberry Pi, you can upgrade libseccomp2 to a supported version from the Debian Repos eg.
> ```
> wget http://ftp.de.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
> dpkg -i libseccomp2_2.5.1-1_armhf.deb
> ```
[[source](https://github.com/docker/for-linux/issues/1196#issuecomment-816600988)]

**Comment by akovalyov** [comment]
just for reference, https://dl-cdn.alpinelinux.org/ and https://alpine.global.ssl.fastly.net are still redirecting from https to http:

```bash
$ curl -I https://dl-cdn.alpinelinux.org/alpine/v3.13/main 
HTTP/2 301 
server: nginx
content-type: text/html
location: http://dl-cdn.alpinelinux.org/alpine/v3.13/main/
```

```bash 
$ curl -I https://alpine.global.ssl.fastly.net/alpine/v3.13/main 
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Content-Length: 162
Server: nginx
Content-Type: text/html
Location: http://alpine.global.ssl.fastly.net/alpine/v3.13/main/
```

**Comment by adrian5** [comment]
I ran into the same `apk` failure with (rootless) **podman**. Strangely enough, `nslookup` worked fine from within the container!

What worked for me was setting the global dns, i.e. `/etc/containers/containers.conf`:

```toml
dns_servers = [ "1.1.1.1", "8.8.8.8" ]
```

**Comment by hlakioui** [comment]
> @wlechowicz restart docker service solved my issue +1

thank you boss, you save my life

**Comment by coderRPN** [comment]
> For Raspberry Pi:
> 
> > The answer is this: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements
> > (alpine 3.13 isn't compatible with raspberry pi os by default due to some outdated package)
> 
> [[source](https://github.com/docker/for-linux/issues/1196#issuecomment-774490539)]
> 
> > For Raspberry Pi, you can upgrade libseccomp2 to a supported version from the Debian Repos eg.
> > ```
> > wget http://ftp.de.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
> > dpkg -i libseccomp2_2.5.1-1_armhf.deb
> > ```
> 
> [[source](https://github.com/docker/for-linux/issues/1196#issuecomment-816600988)]

Same issue exists for apline 3.14 and this solution works

**Comment by hamedsahebi** [comment]
I had the same issue. 
Changing the Alpin version solved mine.  alpin:3.6

**Comment by S474N** [comment]
Actual version is 2.5.3-2

For Raspberry Pi, you can upgrade libseccomp2 to a supported version from the Debian Repos eg.
```
wget http://ftp.de.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.3-2_armhf.deb
dpkg -i libseccomp2_2.5.3-2_armhf.deb

**Comment by pluv1a** [comment]
I used the host network mode to run alpine and the issue was solved:
```bash
docker run -it --network host alpine
```

**Comment by codeninja-ru** [comment]
this helped me https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#musl_1.2

there are several solutions

so I had to download default.json, change one line and pass --security-opt=seccomp=default.json to docker run

**Comment by lovecoding-git** [comment]
> @andyshinn , RE: [#334 (comment)](https://github.com/gliderlabs/docker-alpine/issues/334#issuecomment-330096922)
> 
> It was a DNS error for me. By setting `/etc/docker/daemon.json` with,
> 
> ```
> {
>   "dns": ["8.8.8.8"]
> }
> ```
> 
> and then restarting docker with,
> 
> ```
> sudo service docker restart
> ```
> 
> I was able to build images again.


**-In Windows**
```
C:\Users\Administrator\.docker\daemon.json


```

And add this line.

```
{
    ...
    "dns": ["8.8.8.8"]
}
```

**Comment by fullbl** [comment]
it happens to me if I run 
```docker compose up```,
but it doesn't if I run
```docker-compose up```

**Comment by blockloop** [comment]
My fix for drone was setting the repository as `Trusted` under the repo settings in drone and then adding this to the docker build steps:

```
steps:
  -
    name: docker
    image: plugins/docker
    network_mode: host   <----- this 
```

**Comment by Startouf** [comment]
Similar error happen to me when I try to build docker images from within my kubernetes cluster but my workflow is more complex

1. Locally I build a small docker image with awscli/docker/bash/git

```
FROM docker:latest
# Update & Upgrade OS
RUN apk update
RUN apk upgrade
# https://github.com/aws/aws-cli/issues/4971#issuecomment-1330633153
COPY --from=devopscorner/aws-cli:latest /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=devopscorner/aws-cli:latest /usr/local/bin/ /usr/local/bin/
RUN apk add bash git
```

2. My jenkins (deployed itself on a kubernetes cluster) has some pipelines that spawn some pods that grab this image

```
node(POD_LABEL) {

  stage('Clone') {
    git url: 'https://github.com/example/example/', branch: '${build_branch_name}', credentialsId: 'github-app'

    container('aws-dockerizer') {
      stage('Build and deploy') {
        withAWS(credentials: 'aws-credentials', region: 'eu-central-1') {
          sh '''#!/usr/bin/env bash
            git config --global --add safe.directory ${WORKSPACE}
            scripts/build_and_push_docker_image_to_aws.sh
          '''
        }
      }
    }
  }  

}
```

4. The script runs a docker build step that builds my application image with some dependencies, here is an extract of the Dockerfile being built

```
FROM ruby:3.1.2-alpine
RUN apk add --update --no-cache   binutils-gold   build-base   curl   file   g++   gcc   git   less   libc-dev   htop   libffi-dev   libgcrypt-dev   libstdc++   libxml2-dev   libxslt-dev   linux-headers   make   netcat-openbsd   nodejs   yarn   openssl   pkgconfig   postgresql-dev   ruby-full   tzdata
```

I run into the following errors from the jenkins-spawned pod

```
#6 4.372 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
#6 9.404 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
#6 9.404 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/main: temporary error (try again later)
#6 14.41 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.16/community: temporary error (try again later)
```

So I don't really have a sysadmin-like access, my image is being built from a pod connected to docker via a volume mount on the docker socket. It make it hard to run any OS/config patch

```
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: aws-dockerizer
    image: example/aws-dockerizer:0.1.3
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
```

**Comment by Startouf** [comment]
> Since there are times when the bridge is disturbing, it is successful if you execute it as host. `docker build -t hoge:latest . --network=host`

After struggling for so long with what I though was a kubernetes specific docker-in-docker issue, I ended up adding the `--network=host` in my scripts commands and it fixed it. I should have tried that first instead of going nuts.

**Comment by overbost** [comment]
I have the same issue with "slow" internet connection. Is "slow" for Docker, maybe it have low parameter for "temporary error"

**Comment by exotexot** [comment]
Still happening...

**Comment by axisofentropy** [comment]
I also had this issue randomly building `ingress-nginx` images on Docker Desktop.

```
0.260 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz                  
5.295 WARNING: updating https://dl-cdn.alpinelinux.org/alpine/v3.18/main: temporary error (try again later)                                                                                               
5.295 fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
10.41 WARNING: updating https://dl-cdn.alpinelinux.org/alpine/v3.18/community: temporary error (try again later)
```

I added the `"dns": ["8.8.8.8"]` line to the Docker Desktop config and now it builds consistently.

**Comment by dvdn** [comment]
Same issue trying to build `python:3.11-alpine`.
Solved by adding another dns, like '9.9.9.9' (Quad9), in my existing list in `/etc/docker/daemon.json` :
```
{
        "dns": ["42.xx.xx.42", "9.9.9.9"]
}
```

as described in previous comment > https://github.com/gliderlabs/docker-alpine/issues/334#issuecomment-1135351701

**Comment by build630** [comment]
Any recommendations to address it ?

So far, I have tried 
1. Enabling UnsafeLegacyRenegotiation in /etc/ssl/openssl.cnf
2. Adding DNS to /etc/docker/daemon.json

**Comment by ashikzubair-pge** [comment]
> > Since there are times when the bridge is disturbing, it is successful if you execute it as host. `docker build -t hoge:latest . --network=host`
> 
> After struggling for so long with what I though was a kubernetes specific docker-in-docker issue, I ended up adding the `--network=host` in my scripts commands and it fixed it. I should have tried that first instead of going nuts.

where did u add the netwrok =true ? is that in the jenkins agent config command?

**Comment by Zerwin** [comment]
Ignore everything below, it was an IPV6 problem, not related

-----------------

Figured it out what caused it for me. I had enabled IPV6 on my host and that caused the only DNS server in /etc/resolv.conf to also be IPV6. Disabling IPV6 again caused the build to run through. I could pretty much consistently trigger a failed/successful build by switching between an IPV6 DNS server and an IPV4 DNS server.

Some more info: 
OS: Debian 12
OCI: Podman
Network changes relevant:
`sudo nano /etc/network/interfaces`
and then adding
```
iface eth0 inet6 dhcp
        dhcp6-pd yes
```
(Replace eth0 with whatever your actual network interface is)
Then just restart networking (sudo service networking restart) 

As soon as you get the files once it won't reproduce until you clear all the build caches.

**Comment by OreoProMax** [comment]
> I had this error with Gitlab, i just change docker build command to run with --network host option and it works!我在 Gitlab 上遇到了这个错误，我只需将 docker build 命令更改为使用 --network host 选项运行即可，它可以工作！

works for me

**Comment by OreoProMax** [comment]
> I had this error with Gitlab, i just change docker build command to run with --network host option and it works!

works for me

**Comment by ygxxii** [comment]
In my case, I got this error when `ca-certificates` package is not installed and set `/etc/apk/repositories` to a HTTPS mirror, e.g.:

```text
https://mirrors.aliyun.com/alpine/v3.18/main
https://mirrors.aliyun.com/alpine/v3.18/community
```

To work around, use HTTP mirror:

```Dockerfile
RUN sed -e 's/https:\/\/dl-cdn.alpinelinux.org/http:\/\/mirrors.aliyun.com/g' \
        -i /etc/apk/repositories \
    && apk add --no-cache tzdata
```

**Comment by virtualbeck** [comment]
I used a [borrowed retry function](https://gist.github.com/sj26/88e1c6584397bb7c13bd11108a579746) to get past this:

```
function retry {
  local retries=$1
  shift

  local count=0
  until "$@"; do
    exit=$?
    wait=$((2 ** $count))
    count=$(($count + 1))
    if [ $count -lt $retries ]; then
      echo "Retry $count/$retries exited $exit, retrying in $wait seconds..."
      sleep $wait
    else
      echo "Retry $count/$retries exited $exit, no more retries left."
      return $exit
    fi
  done
  return 0
}
```
    retry 10 apk add --no-cache aws-cli jq

**Comment by aliceisjustplaying** [comment]
Another data point for those who stumble upon this thread: my issue was with Tailscale, needed to turn off stateful filtering with `tailscale up --stateful-filtering=false`

See https://tailscale.com/s/stateful-docker

**Comment by sb1-nicolai** [comment]
For me it was the firewall blocking it. Turned it off temporarily with `sudo systemctl stop firewalld` and it built just fine.

**Comment by ahmadalkhansa** [comment]
Hi, I had the same problem. Docker build creates a container in the default bridge network that will generate the image. Firewalld was blocking the traffic. If this is your case and would still like to use firewalld, you can follow this [blog](https://firewalld.org/2024/04/strictly-filtering-docker-containers) where the interesting part is:

```
firewall-cmd --permanent --zone docker --add-source <docker default network>

firewall-cmd --permanent --new-policy dockerToWorld
firewall-cmd --permanent --policy dockerToWorld --add-ingress-zone docker
firewall-cmd --permanent --policy dockerToWorld --add-egress-zone ANY
firewall-cmd --permanent --policy dockerToWorld --set-target ACCEPT
firewall-cmd --permanent --policy dockerToWorld --add-masquerade

firewall-cmd --reload
```
If the zone doesn't exist please create it beforehand.

To get the default network ip range, you can execute `docker network inspect bridge` where "bridge" is the default network name.

**Comment by englut** [comment]
> Another data point for those who stumble upon this thread: my issue was with Tailscale, needed to turn off stateful filtering with `tailscale up --stateful-filtering=false`
> 
> See https://tailscale.com/s/stateful-docker

Thank you for this. I noticed this issue and thought maybe it was my DNS. But turns out it was Tailscale!

**Comment by stepbystepcode** [comment]
After add dns in docker dameon.json, it works well. Thanks!

**Comment by lifei** [comment]
see this https://stackoverflow.com/questions/74288981/docker-build-error-https-dl-cdn-alpinelinux-org-alpine-v3-14-community-tempo

**Comment by Pictor13** [comment]
It's supposed to work correctly without any particular fix at Docker level.
I fixed my local host system with a `systemctl restart systemd-resolved.service` and Alpine was able to connect correctly to the CDN.
