### ISSUE TITLE
nsenter on Alpine 3.6 won't enter namespaces for a specified PID

### ISSUE THREAD

**Issue by JakeWarner** [gliderlabs/docker-alpine#359]
Steps to reproduce:
1) Start container with Alpine 3.6
2) Start a container within that container.
3) "nsenter -p -i -u -m -n -t <container pid> /bin/sh"

Expected result:
A new /bin/sh session inside of container pid.

Actual result:
nsenter shows the help display again without an error.

Command I ran:
```
/ # nsenter -m -u -i -n -p -t 46 /bin/sh
BusyBox v1.26.2 (2017-10-04 13:37:41 GMT) multi-call binary.

Usage: nsenter [OPTIONS] [PROG [ARGS]]

	-t, --target=PID		Target process to get namespaces from
	-m, --mount[=FILE]		Enter mount namespace
	-u, --uts[=FILE]		Enter UTS namespace (hostname etc)
	-i, --ipc[=FILE]		Enter System V IPC namespace
	-n, --net[=FILE]		Enter network namespace
	-p, --pid[=FILE]		Enter pid namespace
	-U, --user[=FILE]		Enter user namespace
	-S, --setuid=UID		Set uid in entered namespace
	-G, --setgid=GID		Set gid in entered namespace
	--preserve-credentials		Don't touch uids or gids
	-r, --root[=DIR]		Set root directory
	-w, --wd[=DIR]			Set working directory
	-F, --no-fork			Don't fork before exec'ing PROG

```

Changing the order, omitting, or even specifying the direct paths to the namespaces doesn't yield a different result.

If I run "apk add --update util-linux" then try to run the above command, I get:
`.: applet not found`

Thank you

**Comment by JakeWarner** [comment]
Looks like this may be the same issue referenced in: https://github.com/linuxkit/linuxkit/issues/567

**Comment by euanh** [comment]
This problem is fixed as of Busybox 1.28.3r0 in Alpine Edge.

**Comment by lots0logs** [comment]
Seems the issue remains if you try to pass arguments to the command like:
```
docker run -it --rm --privileged --pid=host alpine:edge nsenter -t 1 -m -u -n -i sh -c echo 'hello world'
```

**Comment by subfuzion** [comment]
@lots0logs This is not an issue with alpine, but an issue with `nsenter`. Use `--` to tell `nsenter` to stop trying to parse options. The following should work for you:

    docker run -it --rm --privileged --pid=host alpine:edge nsenter -t 1 -m -u -n -i -- sh -c "echo 'hello world'"

I believe this issue can be closed now.
