### ISSUE TITLE
alpine:3.6 - ERROR: libressl2.5-libtls-2.5.5-r0: BAD signature

### ISSUE THREAD

**Issue by mgebundy** [gliderlabs/docker-alpine#410]
Attempting to build a docker image with `alpine:3.6` fails because of `ERROR: libressl2.5-libtls-2.5.5-r0: BAD signature`.

Until it's fixed, is there a workaround to let the docker image continue building?

Here's the full output:

```
Building ****
Step 1/12 : FROM alpine:3.6 AS base
 ---> 77144d8c6bdc
Step 2/12 : WORKDIR /code
Removing intermediate container 7c40413896ed
 ---> 7dd16c3028ea
Step 3/12 : EXPOSE 80
 ---> Running in 718f130a872c
Removing intermediate container 718f130a872c
 ---> 9c1ec86db592
Step 4/12 : ENV NODE_ENV development
 ---> Running in c1d06cf30df9
Removing intermediate container c1d06cf30df9
 ---> e89a42d6d18d
Step 5/12 : ENV NPM_CONFIG_LOGLEVEL warn
 ---> Running in de845928e2a0
Removing intermediate container de845928e2a0
 ---> 773f2dac4308
Step 6/12 : RUN apk update &&     apk upgrade &&     apk add --no-cache nodejs nodejs-npm curl make gcc g++ python
 ---> Running in bfbf9f107323
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.2-319-gfa3c527048 [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
v3.6.2-305-gbd91af380d [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
OK: 8441 distinct packages available
(1/3) Upgrading busybox (1.26.2-r9 -> 1.26.2-r11)
Executing busybox-1.26.2-r11.post-upgrade
(2/3) Installing libressl2.5-libtls (2.5.5-r0)
ERROR: libressl2.5-libtls-2.5.5-r0: BAD signature
(3/3) Installing ssl_client (1.26.2-r11)
Executing busybox-1.26.2-r11.trigger
1 error; 4 MiB in 12 packages
ERROR: Service '*****' failed to build: The command '/bin/sh -c apk update &&     apk upgrade &&     apk add --no-cache nodejs nodejs-npm curl makegcc g++ python' returned a non-zero code: 1
```

**Comment by cbautista1002** [comment]
FWIW I'm experiencing the same error for two packages (my apk command is different from the above) - `libressl2.5-libtls-2.5.5-r0` and `libressl-dev-2.5.5-r0`:
```
Step 10/25 : RUN apk --no-cache add    bash    gcc    git    gettext-dev    libffi-dev    musl-dev    postgresql-dev    supervisor
 ---> Running in 03cfd7ccda6c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/38) Installing bash (4.3.48-r1)
Executing bash-4.3.48-r1.post-install
(2/38) Installing binutils-libs (2.28-r3)
(3/38) Installing binutils (2.28-r3)
(4/38) Installing gmp (6.1.2-r0)
(5/38) Installing isl (0.17.1-r0)
(6/38) Installing libgomp (6.3.0-r4)
(7/38) Installing libatomic (6.3.0-r4)
(8/38) Installing pkgconf (1.3.7-r0)
(9/38) Installing libgcc (6.3.0-r4)
(10/38) Installing mpfr3 (3.1.5-r0)
(11/38) Installing mpc1 (1.0.3-r0)
(12/38) Installing libstdc++ (6.3.0-r4)
(13/38) Installing gcc (6.3.0-r4)
(14/38) Installing gettext-asprintf (0.19.8.1-r1)
(15/38) Installing libintl (0.19.8.1-r1)
(16/38) Installing libunistring (0.9.7-r0)
(17/38) Installing gettext-libs (0.19.8.1-r1)
(18/38) Installing libxml2 (2.9.5-r0)
(19/38) Installing gettext (0.19.8.1-r1)
(20/38) Installing gettext-dev (0.19.8.1-r1)
(21/38) Installing libssh2 (1.8.0-r1)
(22/38) Installing libcurl (7.60.0-r1)
(23/38) Installing pcre (8.41-r0)
(24/38) Installing git (2.13.5-r0)
(25/38) Installing libffi-dev (3.2.1-r3)
(26/38) Installing musl-dev (1.1.16-r14)
(27/38) Installing libressl2.5-libtls (2.5.5-r0)
(28/38) Installing libressl-dev (2.5.5-r0)
ERROR: libressl2.5-libtls-2.5.5-r0: BAD signature
ERROR: libressl-dev-2.5.5-r0: BAD signature
(29/38) Installing db (5.3.28-r0)
(30/38) Installing libsasl (2.1.26-r10)
(31/38) Installing libldap (2.4.44-r5)
(32/38) Installing libpq (9.6.9-r0)
(33/38) Installing postgresql-libs (9.6.9-r0)
(34/38) Installing postgresql-dev (9.6.9-r0)
(35/38) Installing python2 (2.7.14-r0)
(36/38) Installing py-meld3 (1.0.2-r0)
(37/38) Installing py-setuptools (33.1.1-r1)
(38/38) Installing supervisor (3.2.4-r0)
Executing busybox-1.26.2-r9.trigger
2 errors; 206 MiB in 71 packages
The command '/bin/sh -c apk --no-cache add    bash    gcc    git    gettext-dev    libffi-dev    musl-dev    postgresql-dev    supervisor' returned a non-zero code: 2
```

**Comment by fripoli** [comment]
same here

**Comment by anapsix** [comment]
seems like this got fixed upstream: https://bugs.alpinelinux.org/issues/8939
hoping for image release soon

**Comment by cjbottaro** [comment]
That workaround doesn't work.
```
docker run --rm -it alpine:3.6

# apk add --no-cache libressl-dev libressl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libressl2.5-libtls (2.5.5-r0)
ERROR: libressl2.5-libtls-2.5.5-r0: BAD signature
(2/3) Installing libressl (2.5.5-r0)
ERROR: libressl-2.5.5-r0: BAD signature
(3/3) Installing libressl-dev (2.5.5-r0)
ERROR: libressl-dev-2.5.5-r0: BAD signature
3 errors; 4 MiB in 12 packages
```

**Comment by justindisney** [comment]
I'm also having this issue as of the time of this comment:
```
apk update && apk upgrade &&     apk add --no-cache git openssh
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
v3.6.2-319-gfa3c527048 [http://dl-cdn.alpinelinux.org/alpine/v3.6/main]
v3.6.2-305-gbd91af380d [http://dl-cdn.alpinelinux.org/alpine/v3.6/community]
OK: 8441 distinct packages available
(1/3) Upgrading busybox (1.26.2-r9 -> 1.26.2-r11)
Executing busybox-1.26.2-r11.post-upgrade
(2/3) Installing libressl2.5-libtls (2.5.5-r0)
ERROR: libressl2.5-libtls-2.5.5-r0: BAD signature
```

However, removing the `apk upgrade` command _did_ seem to get around the problem for me.

**Comment by rommik** [comment]
Same issue for me. Is this due to a bad package not bumping a version?

**Comment by g0blin79** [comment]
I confirm the same problem also with python:3.6-alpine3.6

**Comment by ncopa** [comment]
I am looking into it...

**Comment by ncopa** [comment]
This was due to a revert was done wrong. This should be fixed now and libressl-2.5.5-r2 should be available in 10-15 mins.

Sorry.

**Comment by mgebundy** [comment]
Can confirm, builds are working again! Thanks @ncopa.

**Comment by anapsix** [comment]
there was an issue upstream https://bugs.alpinelinux.org/issues/8939
also see https://github.com/gliderlabs/docker-alpine/issues/410
still happening intermittently

**Comment by orange-oranje** [comment]
running it again and again makes the ERROR come for different packages. It got fixed automatically after a few attempts. I don't know why , but got fixed

**Comment by hardikdr** [comment]
I just observed the same issue also with `alpine:3.12`
```
Step 5/10 : FROM alpine:3.12
3.12: Pulling from library/alpine
188c0c94c7c5: Pull complete
Digest: sha256:c0e9560cda118f9ec63ddefb4a173a2b2a0347082d7dff7dc14272e7841a5b5a
Status: Downloaded newer image for alpine:3.12
 ---> d6e46aa2470d
Step 6/10 : RUN apk add --update bash curl
 ---> Running in d4b8ecf44c0f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
(1/8) Installing ncurses-terminfo-base (6.2_p20200523-r0)
(2/8) Installing ncurses-libs (6.2_p20200523-r0)
(3/8) Installing readline (8.0.4-r0)
ERROR: Failed to create usr/lib/libformw.so.6.2: No error information
ERROR: ncurses-libs-6.2_p20200523-r0: BAD signature
(4/8) Installing bash (5.0.17-r0)
Executing bash-5.0.17-r0.post-install
(5/8) Installing ca-certificates (20191127-r4)
(6/8) Installing nghttp2-libs (1.41.0-r0)
(7/8) Installing libcurl (7.69.1-r1)
(8/8) Installing curl (7.69.1-r1)
Executing busybox-1.31.1-r19.trigger
Executing ca-certificates-20191127-r4.trigger
1 error; 9 MiB in 21 packages
The command '/bin/sh -c apk add --update bash curl' returned a non-zero code: 1
```
